kadenze:
    login: "myemail@gmail.com"
    password: "mypassword"
download:
    resolution: "720"                              # Video definition to download. Valid values are "720" or "360".
    download_path: "/home/user/videos/kadenze"     # The absolute path to download to
    courses:                                       # Courses to download, as they appear in the URL. You can also use the keyword "all"
            - "all"
